language: python
python:
- '3.6'
install:
- pip install .
script:
- pytest
deploy:
  provider: pypi
  user: jsbroks
  password:
    secure: E1G7SAA+BgvXkLfaK1gG/a648tHAKGYqXmIDsuYdM8NiiLfdCxWuAr6xAa7kTx7oeH0KYAQKFXYr+/NyibtVIEtLr7sWN+nH+vpoUjlnto2kuLnHfDue4Io0w5/JopjycpDNhdiUoxjmgRIhX0vW/ak8lc2T2jvVjLKD4dSrV/fGg4rWE9t18Yfq+O5O/rF4Xbkr5aU/59FcU1/yKkfqnOc1RRNaHlbfn96lzC8VgHD0Ka2AT+X2UXfjJ0LBV1rLqC42IQATpZYZaClT0OpRQZGIsyaSH4dVJB3PSbcPn3bLxY1qUAhyhqn3WQGMYD4/QO9SvlCY7xTZud3NOMinYg/mE2y1ro9JYUq6ZJh7g9HcMMnJQM0Jx0E5ljG5O0jQasrC4kXOaJiMBDuegotNiU3QmixmzAChYpbWtDCptkFqgEs0QI2NmDHzoAs2MK6TASc5NlwixrsRr3vHOPaK/Li1aJAXaolTugCpTxjuIXWpezF8mdOxptsMcI8sy0Hzq7FwRI0epwktWUw6DKrl547Qd849T5fumxzaXbCefs1/mN5ejMtelypU+blnXHpM81aa128DjtgzrRMq5sqwhw01YGA+G4jIIH/YEt4052fXdk5tP+Q8zY3mPNFc5ScwT2o4sX6yskKCmschqe9APH5tXqpl6yORl37A+wvMNac=
  on:
    tags: true